version: 0.1.0
author: "beltran"

train:
  dataset:
    n_mfcc: 40
    augmentations: False

  model:
    layers:
      input_size: 40
      hidden_sizes: [64, 128, 128, 64]
      output_size: 10
    activation: 
      type: "ReLU"

  optimizer:
    type: "SGD"
    lr: 1e-3
    momentum: 0.9

  loop:
    eval_split: 0.2
    n_epochs: 30
    batch_size: 32

  persistence:
    dataset_name: "mydataset"
    model_name: "mymodel"
    add_timestamp: True

  make_report: True

test:
  interactive: False
  path: "data/test/"
  make_report: True