name: "mymodel_20_coeff"
version: 0.1.0

model:
  layers:
    input_size: 20
    hidden_sizes: [1024, 1024, 1024]
    output_size: 10
  activation: 
    type: "ReLU"

optimizer:
  type: "Adam"
  params:
    lr: 1e-6

eval_split: 0.2
epochs: 50
batchsize: 32
earlystop: True